#############################################################################
# Makefile for building: GLTest
# Generated by qmake (2.01a) (Qt 4.8.0) on: Fri Jun 22 19:50:04 2012
# Project:  GLTest.pro
# Template: app
# Command: /home/siok/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake -spec ../../../Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile GLTest.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -I. -I../../../Desktop/Qt/4.8.0/gcc/include/QtCore -I../../../Desktop/Qt/4.8.0/gcc/include/QtGui -I../../../Desktop/Qt/4.8.0/gcc/include/QtOpenGL -I../../../Desktop/Qt/4.8.0/gcc/include -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/siok/QtSDK/Desktop/Qt/4.8.0/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/siok/QtSDK/Desktop/Qt/4.8.0/gcc/lib -L/usr/X11R6/lib -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/siok/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		glwidget.cpp \
		objloader.cpp moc_mainwindow.cpp \
		moc_glwidget.cpp \
		qrc_glslResources.cpp
OBJECTS       = main.o \
		mainwindow.o \
		glwidget.o \
		objloader.o \
		moc_mainwindow.o \
		moc_glwidget.o \
		qrc_glslResources.o
DIST          = ../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/opengl.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		GLTest.pro
QMAKE_TARGET  = GLTest
DESTDIR       = 
TARGET        = GLTest

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: GLTest.pro  ../../../Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++/qmake.conf ../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/opengl.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../../Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile GLTest.pro
../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/opengl.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
../../../Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../../Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile GLTest.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/GLTest1.0.0 || $(MKDIR) .tmp/GLTest1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/GLTest1.0.0/ && $(COPY_FILE) --parents mainwindow.h glwidget.h objloader.h .tmp/GLTest1.0.0/ && $(COPY_FILE) --parents glslResources.qrc .tmp/GLTest1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp glwidget.cpp objloader.cpp .tmp/GLTest1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/GLTest1.0.0/ && (cd `dirname .tmp/GLTest1.0.0` && $(TAR) GLTest1.0.0.tar GLTest1.0.0 && $(COMPRESS) GLTest1.0.0.tar) && $(MOVE) `dirname .tmp/GLTest1.0.0`/GLTest1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GLTest1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_glwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_glwidget.cpp
moc_mainwindow.cpp: mainwindow.h
	/home/siok/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_glwidget.cpp: glwidget.h
	/home/siok/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) glwidget.h -o moc_glwidget.cpp

compiler_rcc_make_all: qrc_glslResources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_glslResources.cpp
qrc_glslResources.cpp: glslResources.qrc \
		program.frag \
		program.vert
	/home/siok/QtSDK/Desktop/Qt/4.8.0/gcc/bin/rcc -name glslResources glslResources.qrc -o qrc_glslResources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		glwidget.h
	/home/siok/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		glwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

glwidget.o: glwidget.cpp glwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o glwidget.cpp

objloader.o: objloader.cpp objloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objloader.o objloader.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

qrc_glslResources.o: qrc_glslResources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_glslResources.o qrc_glslResources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

